spring.application.name=pertemuan11
# Perbaikan: 'postgresql' (pakai g) dan port default 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/praktikum_db
spring.datasource.username=postgres
# Perbaikan: Hilangkan spasi di 'spring.datasource'
spring.datasource.password=astinurul08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Perbaikan: Dialect yang lebih standar untuk PostgreSQL modern
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect